-- ============================================
-- TRIGGER-AUTO-APROBAR-PB-AL-FINALIZAR-TAREA.sql
-- ============================================
-- OBSOLETO DEPRECATED
-- MOTIVO: Este trigger auto-aprobaba el Presupuesto Base cuando
-- una tarea pasaba a estado finalizada = true. Esto causaba el
-- problema de aprobar el PB prematuramente al crear un PF para
-- una tarea finalizada.
-- La lógica correcta ("solo cuando el presupuesto final es aprobado
-- ahí recién se debe aprobar el presupuesto base") se implementó
-- en actions.ts -> aprobarPresupuestoAction.
-- Utilizar el script ELIMINAR-TRIGGER-AUTO-APROBAR-PB.sql en 
-- el SQL Editor de Supabase para removerlo de la base de datos.
-- ============================================
