-- SPC Protocol v20.0: Passwordless Biometric Authentication
-- Migration: WebAuthn Credential Storage
-- Date: 2026-02-03

-- ============================================================================
-- PART 1: Create user_authenticators table
-- ============================================================================
-- This table stores WebAuthn credentials (public keys) for passwordless login
-- Multiple devices per user are supported (phone, laptop, tablet, etc.)

CREATE TABLE IF NOT EXISTS public.user_authenticators (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
    
    -- WebAuthn Credential Data
    credential_id TEXT NOT NULL UNIQUE, -- Base64-encoded credential ID from authenticator
    public_key TEXT NOT NULL,           -- Base64-encoded public key (COSE format)
    counter BIGINT NOT NULL DEFAULT 0,  -- Sign counter for replay attack prevention
    
    -- Metadata
    device_type TEXT,                   -- e.g., "Android Phone", "iPhone", "Windows Hello"
    user_agent TEXT,                    -- Browser/device info for display
    friendly_name TEXT,                 -- User-defined name like "Mi Celular"
    
    -- Security & Audit
    last_used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    -- Constraints
    CONSTRAINT valid_credential_id CHECK (length(credential_id) > 0),
    CONSTRAINT valid_public_key CHECK (length(public_key) > 0)
);

-- ============================================================================
-- PART 2: Indexes for Performance
-- ============================================================================

CREATE INDEX idx_user_authenticators_user_id ON public.user_authenticators(user_id);
CREATE INDEX idx_user_authenticators_credential_id ON public.user_authenticators(credential_id);
CREATE INDEX idx_user_authenticators_last_used ON public.user_authenticators(last_used_at DESC);

-- ============================================================================
-- PART 3: Row Level Security (RLS)
-- ============================================================================

ALTER TABLE public.user_authenticators ENABLE ROW LEVEL SECURITY;

-- Users can only see their own authenticators
CREATE POLICY "Users can view own authenticators"
    ON public.user_authenticators
    FOR SELECT
    USING (auth.uid() = user_id);

-- Users can insert their own authenticators during enrollment
CREATE POLICY "Users can create own authenticators"
    ON public.user_authenticators
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Users can delete their own authenticators (revoke device)
CREATE POLICY "Users can delete own authenticators"
    ON public.user_authenticators
    FOR DELETE
    USING (auth.uid() = user_id);

-- Users can update metadata (friendly_name, last_used_at)
CREATE POLICY "Users can update own authenticators"
    ON public.user_authenticators
    FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- ============================================================================
-- PART 4: Helper Functions
-- ============================================================================

-- Function to get all authenticators for current user (for device management UI)
CREATE OR REPLACE FUNCTION public.get_my_authenticators()
RETURNS TABLE (
    id UUID,
    friendly_name TEXT,
    device_type TEXT,
    created_at TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        ua.id,
        ua.friendly_name,
        ua.device_type,
        ua.created_at,
        ua.last_used_at
    FROM public.user_authenticators ua
    WHERE ua.user_id = auth.uid()
    ORDER BY ua.last_used_at DESC NULLS LAST, ua.created_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- PART 5: Grants
-- ============================================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_authenticators TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_authenticators() TO authenticated;

-- ============================================================================
-- PART 6: Comments
-- ============================================================================

COMMENT ON TABLE public.user_authenticators IS 
'Stores WebAuthn credentials for passwordless biometric authentication. Each row represents one registered device/authenticator.';

COMMENT ON COLUMN public.user_authenticators.credential_id IS 
'Unique identifier for the credential, generated by the authenticator device';

COMMENT ON COLUMN public.user_authenticators.public_key IS 
'Public key (COSE format) used to verify assertions from the authenticator';

COMMENT ON COLUMN public.user_authenticators.counter IS 
'Signature counter to prevent replay attacks. Incremented with each use';

COMMENT ON COLUMN public.user_authenticators.device_type IS 
'Friendly device type (e.g., "Android Phone", "iPhone 15", "Windows Hello")';

COMMENT ON COLUMN public.user_authenticators.friendly_name IS 
'User-defined name for easy identification in device management UI';
